CREATE TABLE User (
  Id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  AboutMe text,
  Alias varchar(255) DEFAULT NULL,
  City varchar(255) DEFAULT NULL,
  CompanyName varchar(255) DEFAULT NULL,
  Country varchar(255) DEFAULT NULL,
  Department varchar(255) DEFAULT NULL,
  Division varchar(255) DEFAULT NULL,
  Email varchar(255) DEFAULT NULL,
  EmailEncodingKey varchar(255) DEFAULT NULL,
  CommunityNickname varchar(255) DEFAULT NULL,
  Fax varchar(255) DEFAULT NULL,
  FirstName varchar(255) DEFAULT NULL,
  LanguageLocaleKey varchar(255) DEFAULT NULL,
  LastModifiedById varchar(255) NOT NULL DEFAULT 'mule@localhost',
  LastModifiedDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LastName varchar(255) DEFAULT NULL,
  LocaleSidKey varchar(255) DEFAULT NULL,
  MobilePhone varchar(255) DEFAULT NULL,
  Phone varchar(255) DEFAULT NULL,
  PostalCode varchar(255) DEFAULT NULL,
  State varchar(255) DEFAULT NULL,
  Street varchar(255) DEFAULT NULL,
  TimeZoneSidKey varchar(255) DEFAULT NULL,
  Title varchar(255) DEFAULT NULL,
  Username varchar(255) NOT NULL,
  ProfileId varchar(255) NOT NULL
)
